apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-cm
  namespace: bankapp
data:
  MYSQL_DATABASE: bankappdb
  MYSQL_HOST: mysql-svc
  MYSQL_PORT: "3306"
  MYSQL_USER: bankuser
  ollama_URL: http://ollama:11434
