apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "manual"
  hostPath:
    path: /mnt/data/mysql

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
  labels:
    app: ollama
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "manual"
  hostPath:
    path: /mnt/data/ollama
