apiVersion: v1
kind: Secret
metadata:
  name: bankapp-secrets
  namespace: bankapp
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: VGVzdEAxMjM=
  MYSQL_USER: YmFua2FwcHVzZXI=
  MYSQL_PASSWORD: VGVzdEAxMjM=
